name: 기능 구현
description: 기능 추가하기
title: "[Feature ⭐] "
labels: ["Feature ⭐"]
body:
  - type: dropdown
    id: feature-type
    attributes:
      label: 종류
      description: 추가할 기능
      options:
        - 메이크파일
        - 라이브러리
        - 그래픽 / UI
        - 구현 로직
        - 네트워크
        - 기타
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 구현 방법

  - type: textarea
    id: related-code
    attributes:
      label: 연관 코드
      description: API 또는 예시 코드

  - type: dropdown
    id: others
    attributes:
      label: 그밖에
      description: 기능의 속성
      options:
        - 기존 코드를 변경해야 함
        - 문서 작성 필요
      multiple: true
