name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ⚙️ Build
        run: make

      - name: 🧪 Run test
        run: make test
